### PR TITLE
Fix errors extracting data from 3.9 gamestate

### PR DESCRIPTION
**Pull request by MichaelMakesGames**
Fixes https://github.com/eliasdoehne/stellaris-dashboard/issues/112

### CODE REVIEW

**Comment by MichaelMakesGames** [comment]
@eliasdoehne These bugs break the dashboard for the current version of the game, and I know a few people who are eager to see it working again! If you are not currently interested in maintaining the project in general, I could potentially help out (either with a fork, or maintaining this repo).

**Review by chennin — APPROVED** [review]

**Review by chennin — APPROVED** [review]
+1 to the rust change too

**Comment by eliasdoehne** [comment]
> @eliasdoehne These bugs break the dashboard for the current version of the game, and I know a few people who are eager to see it working again! If you are not currently interested in maintaining the project in general, I could potentially help out (either with a fork, or maintaining this repo).

Hi @MichaelMakesGames, that's really great, thanks a lot for your fix! I'm really happy to see that there is still some interest in this project.

It's been very difficult for me to take the required time to maintain this project properly. But I am still interested in keeping it in a runnable state and have quite a few ideas I want to add to it.

I am open to the idea of adding additional maintainers so not all changes have to wait for my input and to make it easier for others to contribute. But I have to research and think a bit about how to best set this up.

**Review by eliasdoehne — APPROVED** [review]
:+1:

**Pull request merged**
